EXTENSION = table_materializer
DATA      = table_materializer--1.0.sql
MODULE_big = table_materializer
OBJS      = table_materializer.o

PG_CONFIG  ?= pg_config
PGXS       := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
